defaults: &defaults
  working_directory: ~/ff1randomizer
  docker:
    - image: fiendsoftheelements/netlify-build:alpine

version: 2
jobs:
  build:
    working_directory: ~/ff1randomizer
    docker:
      - image: fiendsoftheelements/netlify-build:alpine
    steps:
      - checkout
      - run:
          name: publish
          command: |
            set -ex
            cd FF1Blazorizer
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet publish -c Release -o output
              git rev-parse HEAD > output/wwwroot/version.txt
            else
              dotnet publish -c Debug -o output
              git rev-parse HEAD > output/wwwroot/version.txt
            fi
      - persist_to_workspace:
          root: ~/ff1randomizer/FF1Blazorizer/output
          paths:
            - wwwroot

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ff1randomizer/FF1Blazorizer/output
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              netlify deploy --dir=/root/ff1randomizer/FF1Blazorizer/output/wwwroot --prod --site=main
            elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
              netlify deploy --dir=/root/ff1randomizer/FF1Blazorizer/output/wwwroot --prod --site=beta
            else
              netlify deploy --dir=/root/ff1randomizer/FF1Blazorizer/output/wwwroot --prod --site=e09ff967-73b0-4780-bb36-4937361bb133
            fi
         


workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
                - alpha
