defaults: &defaults
  working_directory: ~/ff1randomizer
  docker:
    - image: fiendsoftheelements/netlify-build:alpine

version: 2
jobs:
  build:
    working_directory: ~/ff1randomizer
    docker:
      - image: fiendsoftheelements/netlify-build:alpine
    steps:
      - checkout
      - run:
          name: publish
          command: |
            set -ex
            cd FF1Blazorizer
            
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sed -i 's/NAMELONG/FFRandomizer/' wwwroot/manifest.json
              sed -i 's/NAMESHORT/FFR/' wwwroot/manifest.json
              dotnet publish -c Release -o output
            elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
              sed -i 's/NAMELONG/FFRandomizer - beta/' wwwroot/manifest.json
              sed -i 's/NAMESHORT/FFR β/' wwwroot/manifest.json
              dotnet publish -c Debug -o output
            elif [ "${CIRCLE_BRANCH}" == "alpha" ]; then
              sed -i 's/NAMELONG/FFRandomizer - alpha/' wwwroot/manifest.json
              sed -i 's/NAMESHORT/FFR α/' wwwroot/manifest.json
              dotnet publish -c Debug -o output
            else
              dotnet publis -c Debug -o output
            fi
            
            git rev-parse HEAD > output/wwwroot/version.txt
      - persist_to_workspace:
          root: ~/ff1randomizer/FF1Blazorizer/output
          paths:
            - wwwroot

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ff1randomizer/FF1Blazorizer/output
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              netlify deploy --dir=/root/ff1randomizer/FF1Blazorizer/output/wwwroot --prod --site=main
            elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
              netlify deploy --dir=/root/ff1randomizer/FF1Blazorizer/output/wwwroot --prod --site=beta
            else
              netlify deploy --dir=/root/ff1randomizer/FF1Blazorizer/output/wwwroot --prod --site=61141991-cfa6-4a2e-ab6b-187b1611a2e4
            fi
         


workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
                - alpha
