defaults: &defaults
  working_directory: ~/ff1randomizer
  docker:
    - image: circleci/node:8

version: 2
jobs:
  build:
    working_directory: ~/ff1randomizer
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    steps:
      - checkout
      - run:
          name: publish
          command: |
            set -ex
            cd FF1Blazorizer
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet publish -c Release
              git rev-parse HEAD > bin/Release/netstandard2.1/publish/FF1Blazorizer/dist/version.txt
            else
              dotnet publish -c Debug
              git rev-parse HEAD > bin/Debug/netstandard2.1/publish/FF1Blazorizer/dist/version.txt
            fi
      - persist_to_workspace:
          root: ~/ff1randomizer
          paths:
            - FF1Blazorizer

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ff1randomizer
      - run:
          name: deploy
          command: |
            set -ex
            mkdir -p ~/.ssh
            cp .ssh/known_hosts ~/.ssh/known_hosts
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pushd FF1Blazorizer/bin/Release/netstandard2.1/publish/FF1Blazorizer/dist
            else
              pushd FF1Blazorizer/bin/Debug/netstandard2.1/publish/FF1Blazorizer/dist
            fi
            tar cvzf ../../../../../../../FF1Blazorizer.tar.gz .
            popd
            scp FF1Blazorizer.tar.gz circle@finalfantasyrandomizer.com:FF1Blazorizer.tar.gz
            ssh circle@finalfantasyrandomizer.com "./deployff1rblazor.sh $CIRCLE_BRANCH"

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
                - alpha
