defaults: &defaults
  working_directory: ~/ff1randomizer
  docker:
    - image: fiendsoftheelements/netlify-build:alpine

version: 2
jobs:
  build:
    working_directory: ~/ff1randomizer
    docker:
      - image: fiendsoftheelements/netlify-build:alpine
    steps:
      - checkout
      - run:
          name: publish
          command: |
            set -ex
            cd FF1Blazorizer
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet publish -c Release -o output
              git rev-parse HEAD > output/wwwroot/version.txt
            else
              dotnet publish -c Debug -o output
              git rev-parse HEAD > output/wwwroot/version.txt
            fi
      - persist_to_workspace:
          root: output
          paths:
            - wwwroot

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: tmp/output
      - run:
          name: deploy
          command: "netlify deploy --dir=/tmp/output/wwwroot --prod"


workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
                - alpha
